# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.85352615 0.1292242  0.2225224 ]
  [0.61603967 0.67273202 0.39689964]
  [0.19631157 0.83142724 0.38145673]]

 [[0.31071973 0.3189449  0.06602475]
  [0.63133839 0.16307104 0.97900083]
  [0.75578531 0.88565458 0.05160639]]

 [[0.57299301 0.43830392 0.50109122]
  [0.73956382 0.33458726 0.29192815]
  [0.65985654 0.75661564 0.72404709]]]


# 2. Create a 5x5 matrix with values 1,2,3,4,5 just below the diagonal


In [2]:
import numpy as np
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern¶

In [3]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.06598536 0.70455354 0.82647508 0.44843333 0.50002725]
 [0.73785796 0.83890215 0.88962862 0.09328417 0.65249028]
 [0.17724081 0.33998175 0.59871296 0.67809348 0.67002933]
 [0.36272817 0.73764965 0.99816192 0.17154262 0.38651936]
 [0.95706822 0.70258064 0.2126377  0.37516871 0.64913908]]
After normalization:
[[0.         0.68502922 0.81582154 0.41027418 0.46562197]
 [0.72075681 0.82915279 0.88357002 0.02928502 0.62917794]
 [0.1193502  0.29393186 0.57148788 0.65664397 0.6479931 ]
 [0.31833327 0.72053334 1.         0.11323742 0.34385546]
 [0.9559164  0.68291277 0.15732249 0.33167896 0.62558291]]


# 5. How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([1, 2, 3 , 4, 5, 6])
print("Array1: ",array1)
array2 = [10, 9, 8, 7, 6, 5]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [1 2 3 4 5 6]
Array2:  [10, 9, 8, 7, 6, 5]
Common values between two arrays:
[5 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 1 0 0 1]
Second array:
[0 1 1 0 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0 : ")
print(x)

Original array:
[0.6719368  0.26462433 0.80247024 0.41149896 0.92336715 0.37487928
 0.5649753  0.17529967 0.5116052  0.50604612]
Maximum value replaced by 0 : 
[0.6719368  0.26462433 0.80247024 0.41149896 0.         0.37487928
 0.5649753  0.17529967 0.5116052  0.50604612]


# 9. How to print all the values of an array?

In [9]:
import numpy as np
array = np.arange(20)
np. set_printoptions(threshold=np.inf)
print("All values of an array")
print(array)

All values of an array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# 10.Subtract the mean of each row of a matrix

In [10]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3, 6)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.00989704 0.88901576 0.52643677 0.04449937 0.05052407 0.78548806]
 [0.88606159 0.09706171 0.78693665 0.04244393 0.91784536 0.5414153 ]
 [0.73256151 0.26726644 0.99182982 0.26308762 0.53776787 0.3513068 ]]

Subtract the mean of each row of the said matrix:

[[-0.37441314  0.50470558  0.14212659 -0.33981081 -0.3337861   0.40117788]
 [ 0.34076751 -0.44823238  0.24164256 -0.50285016  0.37255127 -0.00387879]
 [ 0.2085915  -0.25670357  0.46785981 -0.26088239  0.01379786 -0.17266321]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?¶

In [11]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 2. 4. 2. 2. 2. 5. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.85043296, 0.8598663 , 1.18922612, 1.93451306, 1.28174968])

# 13.How to find the most frequent value in an array?

In [13]:
import numpy as np
x = np.random.randint(0, 3, 6)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 1 2 0 1]
Most frequent value in the above array:
1


# 14.How to get the n largest values of an array

In [14]:
import numpy as np
x = np.arange(15)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14]


# 15.How to create a record array from a regular array?

In [15]:
import numpy as np
arra1 = np.array([("Teddy", 88.5, 90), ("Adi", 87.5, 99), ("Ritti", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T, names='col1, col2, col3', formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Teddy' '88.5' '90']
 ['Adi' '87.5' '99']
 ['Ritti' '85.5' '91']]

Record array;
[(b'Teddy', 88.5, 90) (b'Adi', 87.5, 99) (b'Ritti', 85.5, 91)]
